### ISSUE TITLE
Nie działa ze stacją 538

### ISSUE THREAD

**Issue by scibi** [bieniu/gios#5]
Cześć,

Jest jakiś problem ze stacją 538. Jak zmienisz w przykładzie z readme stację na 538 to dostaniesz błąd "Invalid sensor data from GIOS API".

Jak dobrze rozumiem wynika to z tego, że dla tej stacji jest większe opóźnienie w danych:

```json
$ curl -s http://api.gios.gov.pl/pjp-api/rest/station/sensors/538 | python -m json.tool
[
    {
        "id": 3654,
        "param": {
            "idParam": 3,
            "paramCode": "PM10",
            "paramFormula": "PM10",
            "paramName": "py\u0142 zawieszony PM10"
        },
        "stationId": 538
    },
    {
        "id": 18038,
        "param": {
            "idParam": 69,
            "paramCode": "PM2.5",
            "paramFormula": "PM2.5",
            "paramName": "py\u0142 zawieszony PM2.5"
        },
        "stationId": 538
    }
]
```

```json
$ curl -s http://api.gios.gov.pl/pjp-api/rest/data/getData/3654 | python -m json.tool | head -20
{
    "key": "PM10",
    "values": [
        {
            "date": "2020-06-12 15:00:00",
            "value": null
        },
        {
            "date": "2020-06-12 14:00:00",
            "value": null
        },
        {
            "date": "2020-06-12 13:00:00",
            "value": 19.07
        },
        {
            "date": "2020-06-12 12:00:00",
            "value": 19.15
        },
        {
```

Może na stacji jest źle ustawiona strefa czasowa? Oddzielnie zapytam GIOŚ.

Pozdrawiam :)

**Comment by bieniu** [comment]
Standardowo API GIOŚ wysyła wartość `null`, dla niektórych sensorów w okolicach pełnej godziny. Po paru minutach pojawia się prawidłowa wartość. Biblioteka radzi sobie z tym sprawdzając najnowszą i poprzednią wartość. Jeśli dwie wartości pod rząd są `null` jest to traktowane jako błędne dane i wołany jest błąd `InvalidSensorsData`.

**Comment by scibi** [comment]
Wiem. Zajrzałem do kodu. Pytanie czy nie lepiej byłoby sprawdzać nie 2 wartości a w pętli do skutku i podawać z kiedy jest najświeższa wartość?

Poobserwowałem jeszcze i jestem na 99% przekonany, że to jest problem z godziną/strefą czasową na stacji. Przez pierwszą cześć godziny są 2 nulle, a później 1. Wysłałem odpowiednie zgłoszenie do GIOŚ i zobaczymy co z tego wyjdzie.

**Comment by bieniu** [comment]
Brak wartości z ostatniego/przedostatniego pomiaru jest uznawana za brak aktualnych danych. Biblioteka nie obsługuje pobierania danych historycznych. Ja już kiedyś zgłaszałem to do GIOŚ i żadnej odpowiedzi nie dostałem.

**Comment by scibi** [comment]
Jakby co to odpisali. Nie sprawdzałem czy faktycznie coś zrobili.

> Szanowny Panie,
> 
> Odpowiadając na poniższy e-mail dotyczący ustawień dla stacji MzWarTolstoj w zakresie pobierania wyników pomiarów ze względu na problemy techniczne nie nastąpiło przesunięcie na czas letni. Pomiary są prowadzone, wyniki są prezentowane w czasie CET (zimowym). Trwają działania zmierzające do ustawienia pobierania danych na czas rzeczywisty, tak aby na portalu wyniki pomiarów z tej stacji były prezentowane tak samo, jak z pozostałych stacji. Po zakończeniu procesu przekażę stosowną informację.
> 
> Z poważaniem,
> [ciach]
